// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: zoo/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Zoo_AddAnimal_FullMethodName = "/zoo.Zoo/AddAnimal"
)

// ZooClient is the client API for Zoo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZooClient interface {
	AddAnimal(ctx context.Context, in *AddAnimalRequest, opts ...grpc.CallOption) (*AddAnimalRequest, error)
}

type zooClient struct {
	cc grpc.ClientConnInterface
}

func NewZooClient(cc grpc.ClientConnInterface) ZooClient {
	return &zooClient{cc}
}

func (c *zooClient) AddAnimal(ctx context.Context, in *AddAnimalRequest, opts ...grpc.CallOption) (*AddAnimalRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAnimalRequest)
	err := c.cc.Invoke(ctx, Zoo_AddAnimal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZooServer is the server API for Zoo service.
// All implementations must embed UnimplementedZooServer
// for forward compatibility.
type ZooServer interface {
	AddAnimal(context.Context, *AddAnimalRequest) (*AddAnimalRequest, error)
	mustEmbedUnimplementedZooServer()
}

// UnimplementedZooServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZooServer struct{}

func (UnimplementedZooServer) AddAnimal(context.Context, *AddAnimalRequest) (*AddAnimalRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAnimal not implemented")
}
func (UnimplementedZooServer) mustEmbedUnimplementedZooServer() {}
func (UnimplementedZooServer) testEmbeddedByValue()             {}

// UnsafeZooServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZooServer will
// result in compilation errors.
type UnsafeZooServer interface {
	mustEmbedUnimplementedZooServer()
}

func RegisterZooServer(s grpc.ServiceRegistrar, srv ZooServer) {
	// If the following call pancis, it indicates UnimplementedZooServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Zoo_ServiceDesc, srv)
}

func _Zoo_AddAnimal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAnimalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZooServer).AddAnimal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Zoo_AddAnimal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZooServer).AddAnimal(ctx, req.(*AddAnimalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zoo_ServiceDesc is the grpc.ServiceDesc for Zoo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zoo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zoo.Zoo",
	HandlerType: (*ZooServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAnimal",
			Handler:    _Zoo_AddAnimal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zoo/service.proto",
}
